---
- name: Install security patches 1/2
  shell: zypper patch -l -y
  become: yes
  register: zypper_patch1
  changed_when: '"Nothing to do." not in zypper_patch1.stdout'
  notify:
  - Request reload VM
  - Abort for Reload VM

- name: Install security patches 2/2
  shell: zypper patch -l -y
  become: yes
  register: zypper_patch2
  changed_when: '"Nothing to do." not in zypper_patch2.stdout'

- name: Update installed packages.
  zypper:
    name: '*'
    state: latest
  become: yes

- include: _clean.yml
