---
- name: Cleanup zypper
  shell: zypper clean
  become: yes
  ignore_errors: true
  changed_when: false

- name: Cleanup snapper
  shell: snapper delete 2-100000
  become: yes
  ignore_errors: true
  changed_when: false

- name: VM Reload if require
  meta: flush_handlers
