---
- name: Install C/C++ standard develop environment.
  shell: zypper in -l -y -t pattern devel_C_C++
  become: yes
  register: zypper_cppdev
  changed_when: '"Nothing to do." not in zypper_cppdev.stdout'

- include: _clean.yml
